options:
  # Github 新版本自动更新
  auto-update: true
  # 装备状态更新周期
  armor-update-interval: 10
  # 是否启用粘液科技护甲效果
  enable-armor-effects: true
  # 插件前缀
  chat-prefix: '&a&lSlimefun &7> '
  # 自动保存周期, 单位为分钟
  auto-save-delay-in-minutes: 10
  # 绿宝石附魔上限 (扩展选项)
  emerald-enchantment-limit: 2
  # 是否在解锁时给玩家烟花让玩家自己放
  research-give-fireworks: true
  # 是否使用洗矿机旧的工作方式
  legacy-ore-washer: false
  # 是否使用除尘机旧的工作方式
  legacy-dust-washer: false
  # 是否使用碎矿机旧的工作方式
  legacy-ore-grinder: true
  # 限制附魔机/祛魔机可承载的附魔等级上限
  # 设置为 0 关闭限制
  enchanter-level-limit: 0
  # 文本语言
  language: zh-CN
  # 启用多语言功能
  enable-translations: true
  # 物品向后兼容模式, 关闭后将会提升服务器性能
  # 并且关闭对 1.13 的向后兼容
  backwards-compatibility: true
guide:
  # 是否默认使用书与笔进行GUI的展示
  default-view-book: false
  # 是否在指南中展示原版物品合成表
  show-vanilla-recipes: true
  # 是否在玩家第一次进入服务器时自动赠送粘液科技指南
  receive-on-first-join: true

researches:
  # 是否允许创造模式玩家免费解锁研究
  free-in-creative-mode: true
  # 是否在解锁时燃放烟花
  enable-fireworks: true
  # 是否使用游戏币替代使用经验解锁
  use-money-unlock: false
  # 经验自动转换到游戏币倍率
  money-multiply: 25.0

URID:
  info-delay: 3000
  custom-ticker-delay: 10
  enable-tickers: true

networks:
  max-size: 200
  cargo-ticker-delay: 0

items:
  # 是否启用以下物品类别
  talismans: true
  backpacks: true
  soulbound: true

# 研究等级，可自行更改
research-ranks:
  - Chicken
  - Cow
  - Spider
  - Villager
  - Beginner
  - Clumsy Student
  - Unskilled Student
  - Incompetent Student
  - Student
  - Clumsy Apprentice
  - Apprentice
  - Skilled Apprentice
  - Upcoming Mage
  - Excellent Mage
  - Young Magician
  - Incompetent Magician
  - Common Magician
  - Magician
  - Proficient Magician
  - Skilled Magician
  - Accustomed Magician
  - Great Magician
  - Clumsy Wizard
  - Wizard
  - Common Wizard
  - Skilled Wizard
  - Great Wizard
  - Impressive Wizard
  - Young Master
  - Clumsy Master
  - Upcoming Master
  - Competent Master
  - Master
  - Skilled Master
  - Excellent Master
  - Great Master
  - Proficient Master
  - The chosen One
